services:
  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile-backend
    image: racehub-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - database
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    # command: [ "sh", "-c", "composer install && composer show doctrine/dbal && php -S 0.0.0.0:8000 -t public" ]
    networks:
      - network_racehub

  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - phpmyadmin
      # - frontend
    networks:
      - network_racehub
  database:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      # - ./dockerinit.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql # Persistencia de datos de MySQL
    ports:
      - "3306:3306" # Puerto de MySQL
    networks:
      - network_racehub
    environment:
      - TZ=UTC

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80" # Acceso a PHPMyAdmin en http://localhost:8080
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - network_racehub

  # Your existing services remain unchanged

  # Add React frontend services
  # running-frontend:
  #   image: node:18-alpine
  #   working_dir: /app
  #   volumes:
  #     - ./running:/app
  #   ports:
  #     - "5173:5173"
  #   command: sh -c "npm install && npm run dev -- --host --port 5173"
  #   environment:
  #     - VITE_API_URL=http://localhost:81/api
  #   networks:
  #     - network_racehub

  # cycling-frontend:
  #   image: node:18-alpine
  #   working_dir: /app
  #   volumes:
  #     - ./cycling:/app
  #   ports:
  #     - "5174:5173"
  #   command: sh -c "npm install && npm run dev -- --host --port 5173"
  #   environment:
  #     - VITE_API_URL=http://localhost:81/api
  #   networks:
  #     - network_racehub

  # trail-frontend:
  #   image: node:18-alpine
  #   working_dir: /app
  #   volumes:
  #     - ./trailrunning:/app
  #   ports:
  #     - "5175:5173"
  #   command: sh -c "npm install && npm run dev -- --host --port 5173"
  #   environment:
  #     - VITE_API_URL=http://localhost:81/api
  #   networks:
  #     - network_racehub

networks:
  network_racehub:
    driver: bridge

volumes:
  db_data: # Volumen para persistir los datos de la base de datos
