when@dev:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler:
            only_exceptions: false
            collect: false
            collect_serializer_data: false

when@prod:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler: false
